[package]
name = "elliptic_curves"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = "4.5.4"
num-traits = "0.2.19"
rand = "0.8.5"
reikna = "0.12.3"
uint = "0.9.5"
